### PR TITLE
CEv1 again

### PR DESCRIPTION
**Pull request by tomalec**
Update to Custom Elements v1 syntax and Polymer 2.

Please note that I change one test behavior, to what I believe match our needs:
- after `dom-bind`` was attached to DOM
  - ~should forward Polymer notification to `imported-template`~
  + should NOT forward Polymer notification to `imported-template` immediately - before its content is stamped
  + once stamped, should forward Polymer notification to `imported-template`

Tests are failing in polyfilled browsers, probably due to HTML Imports bug + shadow DOM v1 quirks which are not taken into account by tests. But, we already [discussed](https://github.com/Starcounter/Minutes/blob/4f1e338d19047d533edcb9c7e7f16042a3e9c382/WCv1MigrationTF/2017-12-04.md) approach to start with Chrome first.

There is also one failing test in chrome, but I think it's related to the way Polymer 2.0 data binding works: setting the same object/value to a property does not trigger notifications

https://travis-ci.org/Starcounter/starcounter-include/builds/312000552#L3263

>test/partialAttribute/nested-html/stamped_from_polymer_template.html » after `dom-bind` was attached to DOM » after `dom-bind` re-set the sub-partial property (just one scope) to the same instance » should forward the notification to `imported-template`

@warpech, @alshakero do you agree to change it?
> test/partialAttribute/nested-html/stamped_from_polymer_template.html » after dom-bind was attached to DOM » after dom-bind re-set the sub-partial property (just one scope) to the same instance » should **NOT** forward the notification to imported-template

### CODE REVIEW

**Comment by alshakero** [comment]
> do you agree to change it? 

Yes. I don't think we have a choice. Polymer does this check before it forwards a notification:
```js
_shouldPropertyChange(property, value, old) {
    // check equality, and ensure (old == NaN, value == NaN) always returns false
    return old !== value && (old === old || value === value);
}
```

**Review by alshakero — APPROVED** [review]
All good

**Comment by warpech** [comment]
Regarding the test that you changed, I thought that the previous way was correct: When `imported-template` stamps the loaded view, it will attach the **current** model for that view. Therefore, it should NOT forward the notification because it is already up to date.

Can you explain what's the flaw in my reasoning here?

**Review by warpech — APPROVED** [review]
This change looks neat, please go with the change of the test if you have a convincing argument why it is better :)

I can see one test is failing in Edge, unrelated to this PR. Please fix it after the PR.

**Comment by tomalec** [comment]
> Regarding the test that you changed, I thought that the previous way was correct: When imported-template stamps the loaded view, it will attach the current model for that view. Therefore, it should NOT forward the notification because it is already up to date.
>
> Can you explain what's the flaw in my reasoning here?

We actually have a test to specify opposite behavior.

1. New partial comes,
2. We do change `href` synchronously,
3. But hold setting `model` until new markup is stamped, not to propagate new model changes to the old markup,
4. We also do not propagate any Polymer notifications to this `.template`, by that time.
5. When html is being stamped we attach the new model to it (it should already contain changes mady in the meantime, so we just set model once, without a need to apply any additional 
notifications)

**Comment by tomalec** [comment]
> I can see one test is failing in Edge, unrelated to this PR. Please fix it after the PR.

Which one?

**Comment by alshakero** [comment]
> Which one? 

This one http://127.0.0.1:8081/components/starcounter-include/test/?grep=composition%2Fcustom%5C.html%20starcounter-include%20when%20imports%20a%20partial%20with%20a%20custom%20composition%20after%20partial%20property%20is%20replaced%20with%20a%20partial%20that%20contains%20a%20default%20composition%20should%20use%20it%20as%20its%20composition

**Comment by tomalec** [comment]
And why do you thinki it's not related to this PR? 

```html
<h2 class=\"style-scope starcounter-include\">Custom Shadow DOM composition</h2>
        <slot name=\"my-slot\" class=\"style-scope starcounter-include\"></slot>
```

As I mentioned in OP
> Tests are failing in polyfilled browsers, probably due to HTML Imports bug + **shadow DOM v1 quirks** which are not taken into account by tests.

I think it is related to this PR, as it's V1 polyfill quirk.

wc.js/SDv1 polyfill does some magic like `style-scope starcounter-include` and who knows what else, that makes sc-include logic (that I'm not so familiar with any longer) not work. I suspect it's due to the change that compares compositions.


Anyway, I'd fix polyfilled browsers support as another step as we agreed.

**Comment by warpech** [comment]
You are right, actually more tests fail in 4.0.0.

I was confused by another failure - one test fails in 3.0.0. But let's forget about that.

**Pull request merged**
