### PR TITLE
Ignore `_ver#s` and `_ver#c$` properties

### PR DESCRIPTION
**Pull request by tomalec**
while building merged HTML URL

quick fix for ignoring Palindrom meta data https://github.com/Starcounter/starcounter-include/issues/37

### CODE REVIEW

**Review by warpech — APPROVED** [review]
Just tested with https://github.com/Starcounter/level1/issues/4017 (2.3.1.6792) and works like a charm!

Can you pls release a version and include it in branch https://github.com/Starcounter/level1/tree/feature/v2.3/level1/4017?

**Comment by tomalec** [comment]
2.4.1 released.
@warpech Should I merge also https://github.com/Starcounter/level1/pull/4232 to https://github.com/Starcounter/level1/tree/feature/v2.3/level1/4017?

**Comment by warpech** [comment]
Why would that be needed?

**Comment by tomalec** [comment]
because there's already released version. Anyways, I already merged it.

**Pull request merged**
