### PR TITLE
Ignore ShadyCSS classes in tests

### PR DESCRIPTION
**Pull request by tomalec**
Problem: tests were failing https://github.com/Starcounter/starcounter-include/issues/81

CSS scoping tests and support will be tracked in https://github.com/Starcounter/starcounter-include/issues/82

### CODE REVIEW

**Review by warpech — APPROVED** [review]
Looks great to me, just a question: Do the lines https://github.com/Starcounter/starcounter-include/blob/48eaf06eac78de1c3d2e4a751b2aa166536eb81f/starcounter-include.html#L493-L497 do anything?

**Comment by tomalec** [comment]
The do

>// polyfill `polyfill-next-selector` if needed

in V0

**Comment by warpech** [comment]
So they should be removed because this element does not support V0 anymore.

**Comment by tomalec** [comment]
Currently, it supports SD v0 https://github.com/Starcounter/starcounter-include/blob/master/starcounter-include.html#L48-L50

As a part of a separate cleanup task, we can remove it.

**Pull request merged**
