### PR TITLE
Deprecate `starcounter-composition` in favor of `declarative-shadow-dom`

### PR DESCRIPTION
**Pull request by tomalec**
Starcounter/starcounter-include/issues/23
Starcounter/RebelsLounge/issues/79

### CODE REVIEW

**Review by alshakero — APPROVED** [review]
Looks perfect to me.

**Comment by tomalec** [comment]
Thanks.

@warpech Should we also push this to 2.3?

**Comment by warpech** [comment]
Yes, please release a version put it to Starcounter branch `v2.3`, then to `develop`

**Comment by tomalec** [comment]
Ok, thx, will do that once I get access to teamcity

**Comment by tomalec** [comment]
Released.

**Pull request merged**
