### PR TITLE
Add `view-model` alias for `partial`

### LINKED ISSUE #21: Alias `partial` with `view-model`
To meet our renaming ideas https://github.com/Starcounter/TechComm/issues/286
and be closer to MVVM terminology, as an alternative to 
```html
<starcounter-include partial="{{JSONwithData}}"></starcounter-include>
```
we could write
```html
<starcounter-include view-model="{{JSONwithData}}"></starcounter-include>
```

### PR DESCRIPTION
**Pull request by tomalec**
fixes Starcounter/starcounter-include/issues/21

### CODE REVIEW

**Comment by warpech** [comment]
Have you tested it? Does it pass tests when you just replace `partial=` with `view-model=`?

**Comment by tomalec** [comment]
Thanks. Sorry, I didn't tested setting it before `createdCallback` I think once we will agree on final naming replacement, we will just replace it everywhere in the code, so we will not have to maintain tests for aliasing

**Comment by warpech** [comment]
I have tried it with KitchenSink, but it seems to not work. View-model changes seem to be not propagated. Can you pls check?

**Comment by tomalec** [comment]
I did and it works

**Review by warpech — APPROVED** [review]
This looks good now. Please release a version and let me know, I will include it in Starcounter 2.3

**Comment by tomalec** [comment]
@warpech Thanks! 
released as [2.2.0](https://github.com/Starcounter/starcounter-include/releases/tag/2.2.0)

**Comment by warpech** [comment]
Thank you. Added to Starcounter 2.3

**Pull request merged**
