### PR TITLE
Improve warning for non-namespaced partials,

### PR DESCRIPTION
**Pull request by tomalec**
Add a reference to the element and view-model.
https://github.com/Starcounter/starcounter-include/issues/55

### CODE REVIEW

**Review by miyconst — APPROVED** [review]
Looks good, but it's just one point of what I wanted. It is important to identify which partial contains the problematic partial, not only the problematic partial.

**Comment by tomalec** [comment]
@miyconst 
>It is important to identify which partial contains the problematic partial, not only the problematic partial.

I don't get it.
Could you specify precisely what would you like to select?
partial view? partial view-model? 

If you open the warning, you get a reference to the `<starcounter-include>` once you click on it, you can see pretty precisely where it is in the entire DOM tree.

Do you mean something like "enclosing partial view"?
Programmatic searching in `<starcounter-include>`  for its parent element that is `starcounter-include` may not be what you want, if you loaded this `starcounter-include` in some other way (`imported-template`, JS-generated code, one of hundreds way to stamp a HTML)

Do you mean "enslosing partial JSON view-model"?
First of all, `<starcounter-include>` is only aware of the JSON subtree it received, not entire JSON served by Palindrom. Even if we would be able to somehow reach it, how deep to the root would you like to get? just once level? At parent "blended partial" - if so how would you identify it?

I really think the current warning is enough, even before you had a direct link to the line of code, so you can put a breakpoint and dig as deep as you want, you have a reference to the node in DOM, so you can get it highlighted an entire document's HTML.

**Comment by miyconst** [comment]
>I really think the current warning is enough, even before you had a direct link to the line of code, so you can put a breakpoint and dig as deep as you want, you have a reference to the node in DOM, so you can get it highlighted an entire document's HTML.

Unfortunately this is true until you start to debug PALMA.

Here is detailed explanation of what I want:

```json
{
    "Html": "/IndexPage.html",
    "Partial": { "Html": "/SubPage.html" }
}
```

```html
<h1>Index page</h1>
<starcounter-include partial="{{model.Partial}}"></starcounter-include>
```

In this case the warning will point to the `/SubPage.html` and the `<starcounter-include>` element which tries to load it.

What I look for is `/IndexPage.html` value and it's `<starcounter-include>`. I hope it's clear enough.

cc @warpech

**Comment by tomalec** [comment]
`<starcounter-include>` does not have any access to anything outside `{ "Html": "/SubPage.html" }` and in my opinion, it shouldn't.

However, you can still access it pretty easily.

Given the reference to the element, you can still access entire
```html
<h1>Index page</h1>
<starcounter-include partial="{{model.Partial}}"></starcounter-include>
```


Could you please share the problem you are experiencing debugging PALMA?

**Comment by miyconst** [comment]
>Could you please share the problem you are experiencing debugging PALMA?

- There is a lot of HTML elements.
- There is a lot of `<starcounter-include>` elements.
- There is a lot of css variables, which makes Chrome console lags significantly.

**Comment by tomalec** [comment]
sc-include_warning


- There is a lot of HTML elements. > but you can easily traverse through parent elements using breadcrumbs
- There is a lot of `<starcounter-include>` elements. > but you got the reference to only one
- There is a lot of CSS variables, which makes Chrome console lags significantly. > that's a problem not solvable by any warning nor by `starcounter-include`. To see the warning you need to open dev tools anyway. To get your model you are 3 clicks away.



Could we have a meeting/call? As I still don't get what's the problem, and what do you need.

**Comment by miyconst** [comment]
@tomalec, as I said, it just some help in debugging, if you don't want to extend `<starcounter-include>`, then leave it like this. When you have 10+ error messages on console, it's much nicer to see list of all HTML templates which have incorrect inclusion rather then perform 10+ * 3 clicks to find out which template to look for.

**Pull request merged**
