### PR TITLE
Use _setPendingPropertyOrPath instead of _notifyPath

### PR DESCRIPTION
**Pull request by alshakero**
To make it Polymer 2.0 friendly. 

Most tests are passing. The ones aren't passing are the ones that depend on `stamping` event. I'll look into it.

### CODE REVIEW

**Comment by alshakero** [comment]
I feel that there is a trivial issue but I can't manage to overcome it. 

Tests are passing in Chrome but nowhere else. Investigation shows that HTML imports are not working. They're working, but not dynamically, in other words: 

https://github.com/Juicy/imported-template/blob/63467b2d58e35a15281ccaa0db2755928658f025/imported-template.html#L53-L57

The `link.rel = "import";` part isn't taking effect. To see that, throw a `debugger` inside `onload` and see `this.import` type.

**Comment by warpech** [comment]
Related? https://github.com/webcomponents/html-imports/issues/68

**Comment by alshakero** [comment]
@warpech not really, because apparently we gave in and appended the `<link />` to `<head />` https://github.com/Juicy/imported-template/blob/master/imported-template.html#L146-L148

But that issue helped a bit. I'll dig deeper in that direction.

**Comment by warpech** [comment]
Maybe you should use `setAttribute` instead of a property? This is what some HTML Imports tests are using, AFAIS: https://github.com/webcomponents/html-imports/blob/master/tests/html/dynamic.html#L57-L59

**Comment by alshakero** [comment]
I tried too many things it grew chaotic. I'll focus on `imported-template` and then come back here.

**Comment by warpech** [comment]
Thank you. Starcouner 2.3.1-related issues have priority over Starcounter 2.4-related ones.

**Comment by warpech** [comment]
Closing in favor of https://github.com/Starcounter/starcounter-include/pull/68.

Thanks @alshakero and @tomalec

**Pull request closed without merging**
