### PR TITLE
Fix aliasing partial with viewModel, when set before upgrade.

### PR DESCRIPTION
**Pull request by tomalec**
https://github.com/Starcounter/starcounter-include/issues/21

### CODE REVIEW

**Comment by tomalec** [comment]
Related to https://github.com/Starcounter/starcounter-include/issues/38

**Comment by warpech** [comment]
Did you test this in an app? For me KitchenSink navigation does not work after this change:

I am testing this by:

1. Run KitchenSink
2. Run CompositionProvider
3. In CompositionEditor, `cd src/CompositionEditor`
4. `bower install starcounter-include#fix-aliasing-viewModel`
5. `bower install starcounter/starcounter-layout-html-editor#starcounter-include-3.x`
6. Run CompositionEditor
7. Go to `localhost:8080/kitchensink` and try clicking on navigation in the left menu

Unfortunately the problem seems to be introduced in https://github.com/Starcounter/starcounter-include/pull/46 :(

**Comment by tomalec** [comment]
:( I tested it with Products + Images 

I think It's really the time to set up Polymer's Tattoo before proceeding with any changes to our frontend stack.

**Comment by tomalec** [comment]
And integrate this tattoo with our teamcity somehow.

**Review by warpech — APPROVED** [review]
Anyway it looks like this PR is good to go. 

Regarding KitchenSink, I have started another issue: https://github.com/Starcounter/starcounter-include/issues/48

Regarding testing let's please continue in https://github.com/Starcounter/RebelsLounge/issues/64.

**Pull request merged**
